# Site Settings
title: MyMemo
email: fascamaker.factory@gmail.com
description: >
  Une description bref de ce site, ceci est un blog, un mémo et un wiki perso portant en premier lieu sur le domaine de l'informatique.
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
#url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'
url: "https://fasca.github.io"
twitter_username: Fascamaker
github_username: fasca
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
